config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index' #defini que toda vez que o local host for acessado, a action articles#index será acionada

  resources :articles do
    resources :comments, only: %i[create destroy]
  end

  resources :categories, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {minimum: 10}

  scope :desc_order, -> { order(created_at: :desc) }
  scope :without_highlights, ->(ids) { where("id NOT IN(#{ids})") if ids.present? }
  scope :filter_by_category, ->(category) {where category_id: category.id if category.present? }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :restrict_with_error

  validates :name, 
            presence: true, 
            length: {minimum: 3},
            uniqueness: { case_sensitive: false }

  scope :sorted, -> { order(:name) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
has_many :articles, dependent: :destroy
has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :confirmable,
          :database_authenticatable, 
          :registerable,
          :recoverable, 
          :rememberable, 
          :trackable,
          :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "Você não está autorizado a executar esta ação."
    redirect_back_or_to(root_path)
  end
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include Paginable

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, only: %i[edit update destroy]
  before_action :set_categories, only: %i[new create edit update ]

  def index
    @categories = Category.sorted
    category = @categories.select {|c| c.name == params[:category]} [0] if params[:category].present?

    @highlights = Article.includes(:category, :user)
                         .filter_by_category(category)
                         .desc_order
                         .first(3)

    highlights_ids = @highlights.any? ? @highlights.pluck(:id).join(',') : nil

    @articles = Article.includes(:category, :user)
                       .without_highlights(highlights_ids)
                       .filter_by_category(category)
                       .desc_order
                       .page(current_page)
  end

  def show
    @article = Article.includes(comments: :user).find(params[:id])
    authorize @article
  end

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article, notice: "Artigo criado com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Artigo atualizado com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, notice: "Artigo excluído com sucesso."
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :category_id)
  end

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end

  def set_categories
    @categories = Category.sorted
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = policy_scope(Category.sorted)
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Categoria criada com sucesso." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Categoria atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    if @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Categoria excluída com sucesso." }
      format.json { head :no_content }
      end
    else
      redirect_to categories_url, alert: @category.errors.messages[:base][0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      authorize @category
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def create
    @article.comments.create(comment_params.to_h.merge!({user_id: current_user.id}))
    redirect_to article_path(@article), notice: 'Comentário criado com sucesso.'
  end

  def destroy
    comment = @article.comments.find(params[:id])
    authorize comment

    comment.destroy
    redirect_to article_path(@article), notice: 'Comentário excluído com sucesso.'
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

end

app/controllers/concerns/paginable.rb
module Paginable
  protected
  def current_page
    (params[:page] || 1).to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if(condition, template, record)
    render template, record if condition
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def mes_dia_ano(datetime)
    datetime.strftime('%B %e, %Y')
  end
end
# nessa pasta ficam os métodos que criei para usar nas views. Essa formatação do date time é feita conforme o site https://apidock.com/ruby/DateTime/strftime

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_about.html.erb
<div class="p-4 mb-3 bg-body-tertiary rounded">
    <h4 class="fst-italic">About</h4>
    <p class="mb-0">Olá! Eu sou Locke Lamora, e este é o espaço onde compartilho minhas aventuras e descobertas no incrível universo de Minecraft. Entre construções criativas, explorações misteriosas e batalhas épicas, cada sessão se transforma em uma nova história. Acompanhe meu blog para explorar comigo, descobrir dicas e se inspirar em tudo o que este jogo incrível tem a oferecer. Sinta-se a vontade para publicar seus próprios relatos. Bem-vindo à jornada!</p>
</div>

app/views/articles/_article.html.erb
<article class="blog-post">
  <h2 class="display-5 link-body-emphasis mb-1"><%= article.title %></h2>
    <p class="blog-post-meta">
      <%= render 'article_details', article: article %>
    </p>
    <p><%= truncate(article.body, length: 150) %></p>
    <p><%= link_to 'Continue lendo...', article, class: 'btn btn-link' %></p>

  <div class='d-flex gap-2'>
    <%= link_to 'Editar', edit_article_path(article), 
    class: "btn btn-outline-secondary" if policy(article).update? %>

    <%= button_to 'Excluir', 
      article_path(article), 
      method: :delete,
      data: {confirm: "Você tem certeza?"},
      class: "btn btn-outline-danger" if policy(article).destroy? %>
  </div>
</article>

app/views/articles/_article_details.html.erb
<%= mes_dia_ano(article.created_at) %> por
<%= article.user.email %> in 
<%= article.category.name %>

app/views/articles/_elsewhere.html.erb
<div class="p-4">
    <h4 class="fst-italic">Social</h4>
    <ol class="list-unstyled">
        <li><a href="https://github.com/LockeLamora2018" target='_blank'>GitHub</a></li>
        <li><a href="https://x.com/" target='_blank'>Twitter</a></li>
        <li><a href="https://www.facebook.com/" target='_blank'>Facebook</a></li>
    </ol>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for article do |f| %>
    <%= f.input :title %>
    <%= f.input :body, input_html: { rows: 10 }%>
    <%= f.association :category, collection: @categories, prompt: "Escolha uma categoria" %>

    <br>

    <p>
        <%= f.button :submit, class: 'btn btn-outline-success' %>
        <%= link_to 'Voltar', root_path, class: 'btn btn-outline-secondary' %>
    </p>
    
<% end %>

app/views/articles/_longer_featured.html.erb
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
  <div class="col-lg-6 px-0">
    <h1 class="display-4 fst-italic"><%= article.title %></h1>
    <p class="lead my-3"><%= truncate(article.body, length: 100) %></p>
    <p class="lead mb-0">
      <%= link_to 'Continue lendo...', article, class: "text-body-emphasis fw-bold"%>
    </p>
  </div>
</div>

app/views/articles/_medium_featured.html.erb
<div class="col-md-6">
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary-emphasis">
        <%= article.category.name %>
      </strong>

      <h3 class="mb-0"><%= article.title %></h3>

      <div class="mb-1 text-body-secondary">
        <%= render 'article_details', article: article %>
      </div>

      <p class="card-text mb-auto">
        <%= truncate(article.body, length: 80) %>
        </p>
      <%= link_to 'Continue lendo...', article, class: "icon-link gap-1 icon-link-hover stretched-link"%>
    </div>
  </div>
</div>

app/views/articles/_pagination.html.erb
<nav class="blog-pagination" aria-label="Pagination">
    <%= link_to_next_page @articles, "Antigo", class: "btn btn-outline-primary" %>
    <%= link_to_previous_page @articles, "Recente", class: "btn btn-outline-primary" %>
</nav>

app/views/articles/_right_side.html.erb
<div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
        <%= render 'about' %>
        <%= render 'elsewhere' %>
</div>

app/views/articles/edit.html.erb
<h1> Atualizar Artigo </h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<%= render_if @highlights[0].present?, 'longer_featured', article: @highlights[0] %> 

<div class="row mb-2">
    <%= render_if @highlights[1].present?, 'medium_featured', article: @highlights[1] %>
    <%= render_if @highlights[2].present?, 'medium_featured', article: @highlights[2] %>
</div>

<div class="row g-5">
    <div class="col-md-8">
        <h3 class="pb-4 mb-4 fst-italic border-bottom">
            Seja muito bem vindo!
        </h3>
        <p>
            <%= link_to 'Novo Artigo', new_article_path, 
            class:"btn btn-outline-primary" if user_signed_in? %>
        </p>
            <%= render @articles %>
            <%= render 'pagination'%>
    </div>
    <%= render 'right_side' %>
</div>

<%= content_for :category_filter do %>
    <div class="nav-scroller py-1 mb-3 border-bottom">
        <nav class="nav nav-underline justify-content-between">
            <% @categories.each do |category| %>
                <%= link_to category.name, root_path(category: category.name), class: "nav-item nav-link link-body-emphasis #{'category-active' if category.name.to_s == params[:category]}" %>
            <% end %>
        </nav>
    </div>
<%end%>

app/views/articles/new.html.erb
<h1> Novo Artigo </h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<article class="blog-post">
  <h2 class="display-5 link-body-emphasis mb-1"><%= @article.title %></h2>

  <p class="blog-post-meta">
    <%= render 'article_details', article: @article %>
  </p>

  <p><%= @article.body %></p>

  <div class='d-flex gap-2'>
    <%= link_to 'Editar', edit_article_path(@article), 
    class: "btn btn-outline-secondary" if policy(@article).update? %>
    
    <%= button_to 'Excluir', 
      article_path(@article), 
      method: :delete,
      data: {confirm: "Você tem certeza?"}, 
      class: "btn btn-outline-danger" if policy(@article).destroy? %>
    
    <%= link_to 'Voltar', root_path, class: 'btn btn-outline-secondary' %>
  </div>

  <h2 class="mt-3">Comentários</h2>
  <%= render @article.comments %>

  <h2>Adicionar um comentário:</h2>
  <% if policy(:comment).create? %>
  <%= render 'comments/form' %>
  <% else %>
  Favor, realizar o login antes de comentar.
  <% end %>
</article>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Nome:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editar categoria" %>

<h1>Editar categoria</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Voltar", categories_path %>
</div>

app/views/categories/index.html.erb
<% content_for :title, "Categorias" %>

<h1>Categorias</h1>

<p>
  <%= link_to 'Nova categoria', new_category_path, 
  class:"btn btn-outline-primary" if policy(:category).new? %>
</p>

<table class= "table table-striped table-hover table-bordered">
  
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ações</th>
    </tr>
  </thead>

<tbody>
  <% @categories.each do |category| %>
  <tr>
    <td><%= render category %></td>
    <td>
      <%= link_to "Editar", edit_category_path(category) if policy(category).edit? %>
      <%= link_to "Excluir", category, 
      method: :delete, data: {confirm: "Você tem certeza?"} if policy(category).destroy? %>
    <td>
  <% end %>
</div>
</tbody>
</table>

app/views/categories/new.html.erb
<% content_for :title, "Nova categoria" %>

<h1>Nova categoria</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Voltar para Categorias", categories_path %>
</div>

app/views/categories/show.html.erb
<%= render @category %>

<div>
  <%= link_to "Atualizar categoria", edit_category_path(@category) %> |
  <%= link_to "Voltar para Categorias", categories_path %>

  <%= button_to "Excluir categoria", @category, method: :delete %>
</div>

app/views/comments/_comment.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= mes_dia_ano(comment.created_at) %></h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Commenter: <%= comment.user.email%></h6>
    <p class="card-text"><%= comment.body %></p>
    <%= button_to 'Excluir', 
      article_comment_path(@article, comment), 
      method: :delete,
      data: {confirm: "Você tem certeza?"}, 
      class: "btn btn-outline-danger" if policy(comment).destroy? %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@article, @article.comments.build] do |f| %>
<div class="form-inputs">
    <%= f.input :body, input_html: { rows: 10} %>
</div>

<div calss="form-action">
    <%= f.button :submit, class: 'btn btn-outline-primary'%>
</div>
<%end%>

app/views/layouts/_account_links.html.erb
<% if user_signed_in?%>
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.email %>
  </button>
  <ul class="dropdown-menu">
    <li>
        <%= link_to 'Editar usuário', edit_user_registration_path, class: 'dropdown-item'%>
    </li>
    <li><hr class='dropdown-divider'></li>
    <li>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item'%>
    </li>
  </ul>
</div>
<% else %>
    <%= link_to 'Entrar', new_user_session_path, class: 'link-secondary'%>&nbsp; &nbsp;
    <%= link_to 'Inscrever-se', new_user_registration_path, class: 'btn btn-sm btn-outline-secondary'%>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

<% end %>

<% if alert.present? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-5 text-center text-body-secondary bg-body-tertiary">
<p>Template de blog criado para <a href="https://getbootstrap.com/">Bootstrap</a> por <a href="https://twitter.com/mdo">@mdo</a>.</p>
<p class="mb-0">
  <a href="#">voltar ao início</a>
</p>
</footer>

app/views/layouts/_topnavbar.html.erb
<div class="container">
<header class="border-bottom lh-1 py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <%= link_to 'Categorias', categories_path, 
      class:"link-secondary" if policy(:category).index? %>
    </div>

    <div class="col-4 text-center">
      <%= link_to 'Minecraft Land', root_path, class:"blog-header-logo text-dark" %>
    </div>

    <div class="col-4 d-flex justify-content-end align-items-center">
      <%= render 'layouts/account_links' %>
    </div>
  </div>

</header>

  <%= yield :category_filter %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <%= javascript_importmap_tags %>
    <title><%= content_for(:title) || "Projeto Dois" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/topnavbar' %>

    <main class="container">
      <%= render 'layouts/flash_messages'%>

      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>